spring:
  application:
    name: code-ai-generate-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_generate
    username: root
    password: root
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.guozy.codeaigenerate.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


